INSERT INTO public.exercises
(name, muscle_groups, category, equipment_required, difficulty, sets_default, reps_default, duration_seconds, instructions, coaching_cue)
VALUES

-- BODYWEIGHT — EMPUJE
('Flexiones normales', ARRAY['pecho','tríceps','hombros'], 'upper_body', 'none', 2, 3, 10, NULL, 'Manos al ancho de hombros, cuerpo recto de cabeza a talones. Baja el pecho hasta casi tocar el suelo y empuja hacia arriba.', 'Aprieta el abdomen como si fuera a darte un puñetazo.'),
('Flexiones en diamante', ARRAY['tríceps','pecho'], 'upper_body', 'none', 3, 3, 8, NULL, 'Junta los índices y pulgares formando un diamante bajo el pecho. Mantén los codos cerca del cuerpo al bajar.', 'Los codos apuntan hacia atrás, no hacia los lados.'),
('Flexiones inclinadas', ARRAY['pecho','tríceps'], 'upper_body', 'none', 1, 3, 12, NULL, 'Manos en una superficie elevada (silla, cama). Cuerpo en línea recta. Más fácil que las normales — ideal para empezar.', 'Cuanto más alta la superficie, más fácil. Empieza alto si necesitas.'),
('Flexiones declinadas', ARRAY['pecho superior','hombros'], 'upper_body', 'none', 3, 3, 8, NULL, 'Pies en una superficie elevada, manos en el suelo. Trabaja más la parte alta del pecho y los hombros.', 'No dejes que las caderas suban. Cuerpo recto todo el tiempo.'),
('Pike push-up', ARRAY['hombros','tríceps'], 'upper_body', 'none', 3, 3, 8, NULL, 'Forma una V invertida con el cuerpo. Dobla los codos bajando la cabeza hacia el suelo y empuja arriba.', 'Imagina que quieres apoyar la cabeza justo entre las manos.'),
('Fondos en silla', ARRAY['tríceps','pecho'], 'upper_body', 'none', 2, 3, 10, NULL, 'Manos en el borde de una silla, pies al frente. Baja doblando los codos hasta 90° y empuja hacia arriba.', 'Mantén la espalda pegada al borde de la silla al bajar.'),
('Flexiones con pausa', ARRAY['pecho','tríceps','core'], 'upper_body', 'none', 3, 3, 8, NULL, 'Igual que una flexión normal pero aguanta 2 segundos abajo antes de empujar. Aumenta la dificultad sin cambiar el movimiento.', 'La pausa abajo es donde ocurre el trabajo de verdad.'),

-- BODYWEIGHT — PIERNAS
('Sentadilla', ARRAY['cuádriceps','glúteos','isquiotibiales'], 'lower_body', 'none', 1, 3, 12, NULL, 'Pies al ancho de hombros, punta de los pies ligeramente hacia fuera. Baja como si fueras a sentarte, rodillas alineadas con los pies.', 'Pecho arriba, talones en el suelo durante todo el movimiento.'),
('Sentadilla sumo', ARRAY['glúteos','aductores','cuádriceps'], 'lower_body', 'none', 1, 3, 12, NULL, 'Pies más abiertos que los hombros, puntas hacia fuera 45°. Baja manteniendo la espalda recta.', 'Empuja las rodillas hacia fuera al subir — activa más el glúteo.'),
('Zancada alternada', ARRAY['cuádriceps','glúteos','isquiotibiales'], 'lower_body', 'none', 2, 3, 10, NULL, 'Da un paso al frente, baja la rodilla trasera hacia el suelo sin tocarlo. Alterna piernas.', 'La rodilla delantera no debe pasar la punta del pie.'),
('Zancada inversa', ARRAY['cuádriceps','glúteos'], 'lower_body', 'none', 2, 3, 10, NULL, 'Igual que la zancada pero el paso es hacia atrás. Más fácil de controlar el equilibrio.', 'Mantén el torso erguido. No te inclines hacia adelante.'),
('Sentadilla búlgara', ARRAY['cuádriceps','glúteos'], 'lower_body', 'none', 4, 3, 8, NULL, 'Pie trasero apoyado en una silla. Baja el cuerpo doblando la rodilla delantera. Un ejercicio por pierna.', 'El peso va en el talón del pie de apoyo, no en los dedos.'),
('Puente de glúteo', ARRAY['glúteos','isquiotibiales'], 'lower_body', 'none', 1, 3, 15, NULL, 'Tumbado boca arriba, rodillas dobladas, pies en el suelo. Empuja las caderas hacia arriba apretando el glúteo y baja despacio.', 'Aprieta el glúteo arriba del todo durante 1 segundo antes de bajar.'),
('Puente de glúteo a una pierna', ARRAY['glúteos','core'], 'lower_body', 'none', 3, 3, 10, NULL, 'Igual que el puente pero con una pierna estirada al aire. Alterna piernas.', 'Evita que la cadera del lado libre caiga. Mantén la pelvis nivelada.'),
('Wall sit', ARRAY['cuádriceps','glúteos'], 'lower_body', 'none', 2, 3, NULL, 45, 'Espalda pegada a la pared, rodillas a 90°. Aguanta la posición el tiempo indicado.', 'Pies bien apoyados, rodillas alineadas con los tobillos.'),
('Sentadilla con salto', ARRAY['cuádriceps','glúteos','cardio'], 'lower_body', 'none', 3, 3, 10, NULL, 'Baja a sentadilla y al subir da un salto explosivo. Aterriza suave doblando las rodillas.', 'El aterrizaje suave protege las rodillas. No caigas rígido.'),

-- BODYWEIGHT — CORE
('Plancha frontal', ARRAY['core','hombros'], 'core', 'none', 2, 3, NULL, 30, 'Apoya antebrazos y puntas de pie. Cuerpo recto de cabeza a talones. Aguanta el tiempo indicado.', 'Aprieta el abdomen, el glúteo y los muslos. Todo a la vez.'),
('Plancha lateral', ARRAY['oblicuos','core'], 'core', 'none', 3, 3, NULL, 25, 'Apoya un antebrazo y el canto del pie. Cuerpo recto. Cadera arriba, no la dejes caer.', 'Empuja el suelo con el antebrazo para mantener la cadera elevada.'),
('Dead bug', ARRAY['core','estabilizadores'], 'core', 'none', 2, 3, 10, NULL, 'Tumbado boca arriba, brazos al techo, rodillas a 90°. Baja el brazo derecho y la pierna izquierda simultáneamente sin que la espalda baja se despegue del suelo. Vuelve y alterna.', 'La zona lumbar debe quedarse pegada al suelo todo el tiempo.'),
('Elevación de piernas', ARRAY['core inferior','flexores de cadera'], 'core', 'none', 3, 3, 12, NULL, 'Tumbado boca arriba, manos bajo los glúteos. Levanta las piernas juntas hasta 90° y baja despacio sin que toquen el suelo.', 'Baja lento — ahí es donde trabaja el abdomen de verdad.'),
('Mountain climbers', ARRAY['core','cardio','hombros'], 'core', 'none', 3, 3, NULL, 30, 'Posición de plancha alta. Lleva rodillas al pecho alternando rápido como si corrieras en el sitio.', 'Las caderas no deben subir. Mantén la posición de plancha firme.'),
('Hollow body', ARRAY['core','estabilizadores'], 'core', 'none', 3, 3, NULL, 25, 'Tumbado boca arriba, brazos extendidos junto a las orejas. Levanta hombros y piernas del suelo unos centímetros. Mantén la espalda baja pegada al suelo.', 'Si es muy difícil, dobla las rodillas para reducir el brazo de palanca.'),
('Crunches', ARRAY['recto abdominal'], 'core', 'none', 1, 3, 15, NULL, 'Tumbado boca arriba, manos detrás de la cabeza. Sube el torso contrayendo el abdomen. Baja controlado.', 'No tires del cuello con las manos. Las manos solo apoyan.'),
('Russian twist', ARRAY['oblicuos','core'], 'core', 'none', 2, 3, 20, NULL, 'Sentado con torso inclinado 45°, rodillas dobladas. Rota el torso de lado a lado. Puedes levantar los pies para más dificultad.', 'El movimiento viene del torso, no de los brazos.'),

-- BODYWEIGHT — CARDIO
('Burpees', ARRAY['full body','cardio'], 'full_body', 'none', 4, 3, 8, NULL, 'De pie → agáchate → salta pies atrás a plancha → flexión opcional → salta pies adelante → salta arriba con brazos al techo.', 'No tienes que ir rápido. Cada repetición bien hecha vale más que cinco caóticas.'),
('Jumping jacks', ARRAY['cardio','hombros'], 'cardio', 'none', 1, 3, NULL, 30, 'De pie, salta abriendo piernas y llevando brazos al techo. Vuelve a la posición inicial.', 'Aterrizaje suave. Si el ruido es problema, hazlos lentos y controlados.'),
('Rodillas al pecho', ARRAY['cardio','core'], 'cardio', 'none', 2, 3, NULL, 30, 'Corre en el sitio llevando las rodillas lo más arriba posible. Brazos en movimiento natural de carrera.', 'Si necesitas menos impacto, hazlo despacio como marcha elevada.'),
('Saltos de tijera', ARRAY['piernas','cardio'], 'cardio', 'none', 2, 3, NULL, 30, 'De pie, salta adelantando una pierna y la contraria hacia atrás, cambiando en el aire como en una zancada saltada.', 'Si no quieres impacto, hazlos sin salto — zancada alternada rápida.'),
('Inchworm', ARRAY['full body','movilidad'], 'full_body', 'none', 2, 3, 8, NULL, 'De pie, inclínate hasta tocar el suelo. Camina con las manos hacia adelante hasta plancha. Camina pies hacia las manos. Levántate.', 'Mantén las piernas lo más rectas posible al caminar con las manos.'),

-- BODYWEIGHT — MOVILIDAD
('Cat-cow', ARRAY['columna','movilidad'], 'mobility', 'none', 1, 1, 10, NULL, 'A cuatro patas. Arquea la espalda subiendo el abdomen (cat) y luego extiéndela bajando el abdomen y levantando la cabeza (cow). Respira profundo en cada posición.', 'Muévete despacio. Nota cada vértebra moviéndose.'),
('Hip circles', ARRAY['cadera','movilidad'], 'mobility', 'none', 1, 2, 10, NULL, 'De pie, manos en caderas. Dibuja círculos amplios con las caderas. Cambia dirección a mitad de serie.', 'Círculos grandes y lentos. Deja que la cadera suelte tensión.'),
('Hip flexor stretch', ARRAY['flexores de cadera','movilidad'], 'mobility', 'none', 1, 2, NULL, 30, 'Rodilla en el suelo en posición de zancada profunda. Empuja la cadera delantera hacia adelante y abajo. Mantén el torso erguido.', 'Si llevas mucho sentado, este ejercicio va a notarse bastante. Normal.'),
('Rotación torácica', ARRAY['columna','movilidad'], 'mobility', 'none', 1, 2, 10, NULL, 'A cuatro patas o sentado. Mano detrás de la cabeza. Rota el torso hacia arriba lo máximo que puedas. Alterna lados.', 'El movimiento viene de la columna torácica (parte media), no de la cadera.'),
('Sentadilla profunda con apoyo', ARRAY['cadera','tobillo','movilidad'], 'mobility', 'none', 1, 1, NULL, 45, 'Agárrate a algo estable (marco de puerta, poste). Baja en sentadilla profunda con talones en el suelo. Aguanta.', 'Si los talones se levantan, no pasa nada. Con tiempo mejorarás.'),
('Pigeon pose', ARRAY['glúteos','cadera','movilidad'], 'mobility', 'none', 1, 2, NULL, 40, 'En el suelo, una pierna doblada delante y la otra estirada detrás. Inclínate hacia adelante sobre la pierna doblada. Un lado por serie.', 'Respira hacia la tensión. No la fuerces — deja que el cuerpo ceda.'),

-- ELÁSTICO DE TUBO — TIRÓN / BÍCEPS / ESPALDA
('Curl de bíceps con elástico', ARRAY['bíceps'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'De pie sobre el elástico, un asa en cada mano. Dobla los codos subiendo las manos hacia los hombros. Baja controlado.', 'Los codos pegados al cuerpo durante todo el movimiento.'),
('Remo con elástico', ARRAY['espalda','bíceps','romboides'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'Ancla el elástico en una puerta a la altura de la cintura. Sentado o de pie, tira de las asas hacia el abdomen doblando los codos. Aprieta la espalda al final.', 'Piensa en juntar los omóplatos cuando llegas al final del movimiento.'),
('Face pull con elástico', ARRAY['hombros posteriores','romboides'], 'upper_body', 'resistance_bands', 2, 3, 15, NULL, 'Ancla el elástico a la altura de la cara. Tira de las asas hacia tu cara, codos hacia fuera y arriba.', 'Los codos deben quedar más altos que las muñecas al final.'),
('Pulldown con elástico', ARRAY['dorsal','bíceps'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'Ancla el elástico arriba (puerta). De rodillas o sentado, tira de las asas hacia los hombros manteniendo los codos cerca del cuerpo.', 'Imagina que quieres meter los codos en los bolsillos traseros.'),
('Curl de martillo con elástico', ARRAY['bíceps','braquial'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'De pie sobre el elástico, asas con agarre neutro (pulgares arriba). Sube las manos hacia los hombros.', 'Igual que el curl normal pero con las palmas mirándose entre sí.'),

-- ELÁSTICO — EMPUJE / TRÍCEPS / HOMBROS
('Press de pecho con elástico', ARRAY['pecho','tríceps','hombros'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'Ancla el elástico a la espalda (sostenlo con los brazos pasando por debajo de los brazos o sujétalo con la espalda). Empuja las asas hacia adelante a la altura del pecho.', 'Controla el retorno — no dejes que el elástico te jale de golpe.'),
('Press de hombro con elástico', ARRAY['hombros','tríceps'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'De pie sobre el elástico, asas a la altura de los hombros. Empuja hacia arriba hasta extender los brazos.', 'No bloquees los codos al final. Deja un pequeño ángulo.'),
('Extensión de tríceps con elástico', ARRAY['tríceps'], 'upper_body', 'resistance_bands', 2, 3, 15, NULL, 'Ancla el elástico arriba. Codos junto a la cabeza, asas detrás de la nuca. Extiende los codos hacia abajo.', 'Solo se mueven los antebrazos. Los codos se quedan quietos.'),
('Elevación lateral con elástico', ARRAY['hombros laterales'], 'upper_body', 'resistance_bands', 2, 3, 15, NULL, 'De pie sobre el elástico, asas a los lados. Sube los brazos hasta la altura de los hombros con codos ligeramente doblados.', 'No uses el impulso. Sube lento, baja más lento todavía.'),
('Elevación frontal con elástico', ARRAY['hombros anteriores'], 'upper_body', 'resistance_bands', 2, 3, 12, NULL, 'De pie sobre el elástico, asas delante. Sube un brazo (o los dos) hacia adelante hasta la altura de los hombros.', 'El movimiento es controlado. No balancees el torso.'),

-- ELÁSTICO — PIERNAS / GLÚTEOS
('Sentadilla con elástico', ARRAY['cuádriceps','glúteos'], 'lower_body', 'resistance_bands', 2, 3, 12, NULL, 'De pie sobre el elástico, asas a los hombros. Haz una sentadilla normal con la resistencia añadida.', 'El elástico te obliga a mantener el torso erguido — aprovéchalo.'),
('Patada de glúteo con elástico', ARRAY['glúteos','isquiotibiales'], 'lower_body', 'resistance_bands', 2, 3, 15, NULL, 'A cuatro patas con el elástico enganchado al tobillo y anclado bajo tus manos. Empuja el pie hacia atrás y arriba apretando el glúteo. Un lado por serie.', 'Extiende la pierna del todo arriba y aprieta el glúteo 1 segundo.'),
('Hip thrust con elástico', ARRAY['glúteos','isquiotibiales'], 'lower_body', 'resistance_bands', 2, 3, 15, NULL, 'Tumbado boca arriba, rodillas dobladas, elástico sobre las caderas sujeto con las manos. Empuja las caderas hacia arriba.', 'Aprieta el glúteo arriba del todo durante 1 segundo. El elástico añade resistencia donde más importa.'),
('Crab walk lateral con elástico', ARRAY['glúteos','abductores'], 'lower_body', 'resistance_bands', 2, 3, 15, NULL, 'Elástico sobre los tobillos. Semi-sentadilla. Da pasos laterales manteniendo la tensión en el elástico.', 'Mantén las rodillas hacia fuera. No las dejes colapsar hacia adentro.'),
('Abducción de cadera con elástico', ARRAY['glúteos','abductores'], 'lower_body', 'resistance_bands', 1, 3, 15, NULL, 'Tumbado de lado, elástico sobre los tobillos. Levanta la pierna de arriba hacia el techo. Baja controlado.', 'Movimiento lento y controlado. Siente el glúteo lateral trabajar.'),
('Zancada con elástico', ARRAY['cuádriceps','glúteos'], 'lower_body', 'resistance_bands', 3, 3, 10, NULL, 'De pie sobre el elástico, asas a los hombros. Haz zancadas alternadas con la resistencia añadida.', 'El elástico te ayuda a mantener el torso recto — no te inclines.'),

-- ELÁSTICO — CORE
('Pallof press con elástico', ARRAY['core','oblicuos','estabilizadores'], 'core', 'resistance_bands', 3, 3, 12, NULL, 'Ancla el elástico a un lado a la altura del pecho. De pie perpendicular al ancla. Empuja las asas hacia adelante extendiendo los brazos y resiste la rotación.', 'El objetivo es no girar. Tu core está trabajando para mantenerte recto.'),
('Rotación de core con elástico', ARRAY['oblicuos','core'], 'core', 'resistance_bands', 2, 3, 12, NULL, 'Ancla el elástico a un lado. De pie con pies firmes. Rota el torso alejándote del ancla y vuelve controlado. Un lado por serie.', 'Los pies no se mueven. Toda la rotación viene del torso.');
